spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:migrations/postgresql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration