spring:
  application:
    name: message-store-ui

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing.sampling.probability: 1.0
  endpoints.web.exposure.include: health

okta:
  oauth2:
    issuer: https://dev-5xk4kg2ztj2u5h3n.us.auth0.com/
    client-id: a3cO6gBMBfVkK6v152UP4SOBRPobj7Qp
    client-secret: REPLACE_ME

messageApi:
  host: REPLACE_ME
  oauth2:
    audience: https://foo.service.com/api/messages

server:
  port: 8090
