apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-application
  template:
    metadata:
      labels:
        app: sample-application
    spec:
      containers:
        - name: sample-application
          image: ci-cd-project/sample-application:latest
          ports:
            - containerPort: 8080
          env:
            - name: node.ip
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Never
